### ISSUE TITLE
Existing wallet does not work

### ISSUE THREAD

**Issue by kdc2000** [DIG-Network/chia-dig-node#6]
When I initially set up the DIG node, I provided the 24 word seed phrase for an existing wallet that I had created with the chia reference software.  The DIG propagation server would give an error message "Failed to create server coin: no spendable coins".

I deleted the seed phrase with "dignode wallet delete", and then used dignode to generate a new seed phrase, synced it, funded it, and then the propagation server was able to find a spendable coin.

**Comment by MichaelTaylor3D** [comment]
I would rather avoid existing wallets because the code is in alpha and I dont want someone to loose there funds over a bug. This is why it was emphasized in the docks to use a dedicated dignode wallet.

The reason it didnt find coins was because the driver code only looks at the first puzzle hash when selecting coins.

Ill be sure to mention this in the docs.
